import { ProjectCategory } from "../app/shared/types/enums"

const categoryLabels: Record<number, string> = {
  [ProjectCategory.WebApi]: "Web API",
  [ProjectCategory.WebApplication]: "Web Application",
  [ProjectCategory.SinglePageApplication]: "Single Page Application",
  [ProjectCategory.ProgressiveWebApp]: "Progressive Web App",
  [ProjectCategory.EcommerceSite]: "E-commerce Site",
  [ProjectCategory.ContentManagementSystem]: "Content Management System",
  [ProjectCategory.MobileApp]: "Mobile App",
  [ProjectCategory.iOSApp]: "iOS App",
  [ProjectCategory.AndroidApp]: "Android App",
  [ProjectCategory.CrossPlatformMobile]: "Cross-Platform Mobile",
  [ProjectCategory.DesktopApp]: "Desktop App",
  [ProjectCategory.WindowsApp]: "Windows App",
  [ProjectCategory.MacApp]: "Mac App",
  [ProjectCategory.LinuxApp]: "Linux App",
  [ProjectCategory.Microservice]: "Microservice",
  [ProjectCategory.BackendService]: "Backend Service",
  [ProjectCategory.WorkerService]: "Worker Service",
  [ProjectCategory.MessageQueueService]: "Message Queue Service",
  [ProjectCategory.GraphQLApi]: "GraphQL API",
  [ProjectCategory.gRPCService]: "gRPC Service",
  [ProjectCategory.CloudNativeApp]: "Cloud Native App",
  [ProjectCategory.ServerlessFunction]: "Serverless Function",
  [ProjectCategory.ContainerizedApp]: "Containerized App",
  [ProjectCategory.InfrastructureAsCode]: "Infrastructure as Code",
  [ProjectCategory.DataPipeline]: "Data Pipeline",
  [ProjectCategory.ETLProcess]: "ETL Process",
  [ProjectCategory.DataWarehouse]: "Data Warehouse",
  [ProjectCategory.BusinessIntelligence]: "Business Intelligence",
  [ProjectCategory.DataScienceProject]: "Data Science Project",
  [ProjectCategory.MachineLearningModel]: "Machine Learning Model",
  [ProjectCategory.Game2D]: "2D Game",
  [ProjectCategory.Game3D]: "3D Game",
  [ProjectCategory.MobileGame]: "Mobile Game",
  [ProjectCategory.IoTApplication]: "IoT Application",
  [ProjectCategory.EmbeddedSystem]: "Embedded System",
  [ProjectCategory.FirmwareProject]: "Firmware Project",
  [ProjectCategory.CI_CDPipeline]: "CI/CD Pipeline",
  [ProjectCategory.AutomationScript]: "Automation Script",
  [ProjectCategory.MonitoringTool]: "Monitoring Tool",
  [ProjectCategory.DevTool]: "Developer Tool",
  [ProjectCategory.LegacyMaintenance]: "Legacy Maintenance",
  [ProjectCategory.MigrationProject]: "Migration Project",
  [ProjectCategory.RefactoringProject]: "Refactoring Project",
  [ProjectCategory.ProofOfConcept]: "Proof of Concept",
  [ProjectCategory.Prototype]: "Prototype",
  [ProjectCategory.MVP]: "MVP",
  [ProjectCategory.LibraryOrPackage]: "Library or Package",
  [ProjectCategory.DocumentationProject]: "Documentation Project",
  [ProjectCategory.OpenSourceProject]: "Open Source Project",
  [ProjectCategory.InternalTool]: "Internal Tool",
  [ProjectCategory.ClientProject]: "Client Project",
  [ProjectCategory.PersonalProject]: "Personal Project",
}

export function getProjectCategoryName(category: number): string {
  return categoryLabels[category] ?? "Unknown"
}
