/* eslint-disable @typescript-eslint/no-unused-vars */
import { useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Check, Pencil, Plus, Trash2, X } from "lucide-react"
import { createEducation, deleteEducation, educationKeys, updateEducation } from "../admin.service"
import { educationQueries } from "../../education/educations.service"
import PaginationControls from "../components/PaginationControls"
import type { Education } from "../../../shared/types"
const PAGE_SIZE = 10
const blank = (): Omit<Education, "id"> => ({ title: "", issuer: "", year: "" })
export default function EducationsPage() {
  const client = useQueryClient(); const { data: educations = [] } = useQuery(educationQueries.list())
  const [page, setPage] = useState(1), [editingId, setEditingId] = useState<string | null>(null), [draft, setDraft] = useState<Omit<Education, "id"> | null>(null), [adding, setAdding] = useState(false), [newRow, setNewRow] = useState(blank)
  const invalidate = () => client.invalidateQueries({ queryKey: educationKeys.all }); const create = useMutation({ mutationFn: () => createEducation(newRow), onSuccess: () => { invalidate(); setAdding(false); setNewRow(blank()); setPage(Math.max(1, Math.ceil((educations.length + 1) / PAGE_SIZE))) } }); const update = useMutation({ mutationFn: ({ id, row }: { id: string; row: Omit<Education, "id"> }) => updateEducation(id, row), onSuccess: () => { invalidate(); setEditingId(null); setDraft(null) } }); const remove = useMutation({ mutationFn: deleteEducation, onSuccess: () => { invalidate(); if (educations.length - 1 <= (page - 1) * PAGE_SIZE && page > 1) setPage(page - 1) } }); const rows = educations.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE)
  const fields = (value: Omit<Education, "id">, change: (value: Omit<Education, "id">) => void) => <div className="grid gap-3 md:grid-cols-3">{(["title", "issuer", "year"] as const).map((field) => <input key={field} value={value[field]} placeholder={field === "issuer" ? "Institution" : field[0].toUpperCase() + field.slice(1)} onChange={(e) => change({ ...value, [field]: e.target.value })} className="bg-transparent border-b border-outline-variant py-2 focus:border-primary focus:outline-none w-full text-on-surface" />)}</div>
  return <div className="space-y-6"><div className="flex items-center justify-between"><h1 className="font-headline text-2xl font-bold">Education</h1><button type="button" onClick={() => setAdding(true)} className="inline-flex cursor-pointer items-center gap-2 rounded-md bg-linear-to-r from-primary to-secondary px-4 py-2 text-sm font-semibold text-on-primary"><Plus className="size-4" />Add education</button></div>{adding ? <form onSubmit={(e) => { e.preventDefault(); create.mutate() }} className="rounded-xl border border-white/10 bg-surface-container-high p-4">{fields(newRow, setNewRow)}<div className="mt-4 flex gap-2"><button className="rounded-md bg-linear-to-r from-primary to-secondary px-4 py-2 text-sm text-on-primary">Save</button><button type="button" onClick={() => setAdding(false)} className="rounded-md bg-surface-container-high border border-outline-variant/30 px-4 py-2 text-sm">Cancel</button></div></form> : null}<section className="overflow-hidden rounded-xl border border-white/10 bg-surface-container-high"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr className="border-b border-white/10">{["Title","Institution","Year","Actions"].map((h) => <th key={h} className="px-4 py-3 font-label text-xs uppercase tracking-widest text-on-surface-variant">{h}</th>)}</tr></thead><tbody>{rows.map((row) => { const editing = editingId === row.id; return <tr key={row.id} className="border-b border-white/5 hover:bg-white/[0.03]">{editing && draft ? <td colSpan={4} className="p-4">{fields(draft, setDraft)}<button type="button" aria-label="Save education" onClick={() => update.mutate({ id: row.id, row: draft })} className="mt-3 size-8 cursor-pointer text-primary"><Check className="m-auto size-4" /></button><button type="button" aria-label="Cancel" onClick={() => { setEditingId(null); setDraft(null) }} className="size-8 cursor-pointer"><X className="m-auto size-4" /></button></td> : <><td className="px-4 py-3">{row.title}</td><td className="px-4 py-3">{row.issuer}</td><td className="px-4 py-3">{row.year}</td><td className="px-4 py-3"><button type="button" aria-label={`Edit ${row.title}`} onClick={() => { const { id: _, ...item } = row; setEditingId(row.id); setDraft(item) }} className="size-8 cursor-pointer text-primary"><Pencil className="m-auto size-4" /></button><button type="button" aria-label={`Delete ${row.title}`} onClick={() => { if (window.confirm(`Delete ${row.title}?`)) remove.mutate(row.id) }} className="size-8 cursor-pointer text-error"><Trash2 className="m-auto size-4" /></button></td></>}</tr> })}{rows.length === 0 ? <tr><td colSpan={4} className="px-4 py-8 text-center text-sm text-on-surface-variant">No education yet.</td></tr> : null}</tbody></table></div><div className="px-4"><PaginationControls currentPage={page} pageSize={PAGE_SIZE} totalItems={educations.length} onPageChange={setPage} /></div></section></div>
}
