export const ProficiencyLevel = {
  Elementary: 0,
  Intermediate: 1,
  Advanced: 2,
  Native: 3,
} as const

export type ProficiencyLevel = (typeof ProficiencyLevel)[keyof typeof ProficiencyLevel]

export const ProjectCategory = {
  WebApi: 0,
  WebApplication: 1,
  SinglePageApplication: 2,
  ProgressiveWebApp: 3,
  EcommerceSite: 4,
  ContentManagementSystem: 5,
  MobileApp: 6,
  iOSApp: 7,
  AndroidApp: 8,
  CrossPlatformMobile: 9,
  DesktopApp: 10,
  WindowsApp: 11,
  MacApp: 12,
  LinuxApp: 13,
  Microservice: 14,
  BackendService: 15,
  WorkerService: 16,
  MessageQueueService: 17,
  GraphQLApi: 18,
  gRPCService: 19,
  CloudNativeApp: 20,
  ServerlessFunction: 21,
  ContainerizedApp: 22,
  InfrastructureAsCode: 23,
  DataPipeline: 24,
  ETLProcess: 25,
  DataWarehouse: 26,
  BusinessIntelligence: 27,
  DataScienceProject: 28,
  MachineLearningModel: 29,
  Game2D: 30,
  Game3D: 31,
  MobileGame: 32,
  IoTApplication: 33,
  EmbeddedSystem: 34,
  FirmwareProject: 35,
  CI_CDPipeline: 36,
  AutomationScript: 37,
  MonitoringTool: 38,
  DevTool: 39,
  LegacyMaintenance: 40,
  MigrationProject: 41,
  RefactoringProject: 42,
  ProofOfConcept: 43,
  Prototype: 44,
  MVP: 45,
  LibraryOrPackage: 46,
  DocumentationProject: 47,
  OpenSourceProject: 48,
  InternalTool: 49,
  ClientProject: 50,
  PersonalProject: 51,
} as const

export type ProjectCategory = (typeof ProjectCategory)[keyof typeof ProjectCategory]
